#!/usr/bin/env python3
"""Generate a C header containing an already-patched cached ABL PE."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def byte_lines(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", required=True, type=Path, help="Original raw ABL/FV input")
    ap.add_argument("--extracted-pe", required=True, type=Path, help="Unwrapped PE before patching")
    ap.add_argument("--patched-pe", required=True, type=Path, help="Patched PE to embed")
    ap.add_argument("--mode", required=True, help="GBL mode used for host prepatching")
    ap.add_argument("--out", required=True, type=Path, help="Output header")
    args = ap.parse_args()

    data = args.patched_pe.read_bytes()
    if not data:
        raise SystemExit("patched PE is empty")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        "/* Auto-generated by scripts/generate-cached-abl-header.py. */\n"
        "#ifndef GBL_GENERATED_CACHED_ABL_BLOB_H_\n"
        "#define GBL_GENERATED_CACHED_ABL_BLOB_H_\n\n"
        f"STATIC CONST UINT32 gCachedAblPeSize = {len(data)}U;\n"
        f"STATIC CONST CHAR8 gCachedAblSourceSha256[] = \"{sha256(args.source)}\";\n"
        f"STATIC CONST CHAR8 gCachedAblExtractedPeSha256[] = \"{sha256(args.extracted_pe)}\";\n"
        f"STATIC CONST CHAR8 gCachedAblPatchedPeSha256[] = \"{sha256(args.patched_pe)}\";\n"
        f"STATIC CONST CHAR8 gCachedAblBuildMode[] = \"mode-{args.mode}\";\n"
        "STATIC CONST UINT8 gCachedAblPe[] = {\n"
        f"{byte_lines(data)}\n"
        "};\n\n"
        "#endif /* GBL_GENERATED_CACHED_ABL_BLOB_H_ */\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
