#!/usr/bin/env python3
"""Generate a cached ABL container C header."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

MAGIC = b"GBL_CACHE_ABL_v1"
MAGIC_SIZE = 16
VERSION = 1
OFF_MAGIC = 0
OFF_VERSION = 16
OFF_PRESENT = 20
OFF_CAPACITY = 24
OFF_PAYLOAD_SIZE = 28
OFF_MODE = 32
OFF_SOURCE_SIZE = 36
OFF_EXTRACTED_SIZE = 40
OFF_SOURCE_SHA = 48
OFF_EXTRACTED_SHA = 112
OFF_PATCHED_SHA = 176
PAYLOAD_OFFSET = 256
DEFAULT_CAPACITY = 2 * 1024 * 1024
EFISP_UTF16LE = b"e\x00f\x00i\x00s\x00p\x00\x00\x00"


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def put_u32(buf: bytearray, off: int, value: int) -> None:
    buf[off : off + 4] = int(value).to_bytes(4, "little")


def put_ascii(buf: bytearray, off: int, text: str, size: int = 64) -> None:
    raw = text.encode("ascii")
    if len(raw) != size:
        raise SystemExit(f"metadata string at {off} must be {size} bytes")
    buf[off : off + size] = raw


def assert_no_efisp_loader_label(data: bytes, path: Path) -> None:
    if EFISP_UTF16LE in data:
        raise SystemExit(
            f"unsafe cached ABL still contains UTF-16 efisp loader label after patching: {path}"
        )


def make_container(
    *,
    capacity: int,
    mode: int,
    source: Path | None,
    extracted_pe: Path | None,
    patched_pe: Path | None,
) -> bytes:
    if capacity <= 0:
        raise SystemExit("capacity must be positive")

    payload = patched_pe.read_bytes()  # type: ignore[union-attr]
    if not payload:
        raise SystemExit("patched PE is empty")
    assert_no_efisp_loader_label(payload, patched_pe)  # type: ignore[arg-type]
    if len(payload) > capacity:
        raise SystemExit(f"patched PE exceeds container capacity ({len(payload)} > {capacity})")

    buf = bytearray(PAYLOAD_OFFSET + capacity + MAGIC_SIZE)
    buf[OFF_MAGIC : OFF_MAGIC + MAGIC_SIZE] = MAGIC
    put_u32(buf, OFF_VERSION, VERSION)
    put_u32(buf, OFF_PRESENT, 1)
    put_u32(buf, OFF_CAPACITY, capacity)
    put_u32(buf, OFF_PAYLOAD_SIZE, len(payload))
    put_u32(buf, OFF_MODE, mode)

    assert source is not None and extracted_pe is not None and patched_pe is not None
    put_u32(buf, OFF_SOURCE_SIZE, source.stat().st_size)
    put_u32(buf, OFF_EXTRACTED_SIZE, extracted_pe.stat().st_size)
    put_ascii(buf, OFF_SOURCE_SHA, sha256(source))
    put_ascii(buf, OFF_EXTRACTED_SHA, sha256(extracted_pe))
    put_ascii(buf, OFF_PATCHED_SHA, sha256(patched_pe))
    buf[PAYLOAD_OFFSET : PAYLOAD_OFFSET + len(payload)] = payload

    buf[PAYLOAD_OFFSET + capacity : PAYLOAD_OFFSET + capacity + MAGIC_SIZE] = MAGIC
    return bytes(buf)


def byte_lines(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", type=Path, help="Original raw ABL/FV input")
    ap.add_argument("--extracted-pe", type=Path, help="Unwrapped PE before patching")
    ap.add_argument("--patched-pe", type=Path, help="Patched PE to embed")
    ap.add_argument("--capacity", type=int, default=DEFAULT_CAPACITY, help="Payload capacity for cached ABL container")
    ap.add_argument("--mode", required=True, type=int, help="GBL mode used for host prepatching")
    ap.add_argument("--out", required=True, type=Path, help="Output header")
    args = ap.parse_args()

    for name in ("source", "extracted_pe", "patched_pe"):
        value = getattr(args, name)
        if value is None:
            raise SystemExit(f"--{name.replace('_', '-')} is required")
        if not value.is_file():
            raise SystemExit(f"missing input: {value}")

    data = make_container(
        capacity=args.capacity,
        mode=args.mode,
        source=args.source,
        extracted_pe=args.extracted_pe,
        patched_pe=args.patched_pe,
    )

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(
        "/* Auto-generated by scripts/generate-cached-abl-header.py. */\n"
        "#ifndef GBL_GENERATED_CACHED_ABL_BLOB_H_\n"
        "#define GBL_GENERATED_CACHED_ABL_BLOB_H_\n\n"
        f"STATIC CONST UINT32 gCachedAblContainerSize = {len(data)}U;\n"
        "STATIC CONST UINT8 gCachedAblContainer[] = {\n"
        f"{byte_lines(data)}\n"
        "};\n\n"
        "#endif /* GBL_GENERATED_CACHED_ABL_BLOB_H_ */\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
